export interface AppRouteDefinition {
  description?: string;
  group: 'dashboard' | 'people-org' | 'work' | 'governance' | 'admin';
  path: string;
  title: string;
  allowedRoles?: string[];
}

export const appRoutes: AppRouteDefinition[] = [
  {
    group: 'dashboard',
    path: '/',
    title: 'Workload Overview',
  },
  {
    description: 'Diagnostic comparison of planned staffing and observed work.',
    group: 'dashboard',
    path: '/dashboard/planned-vs-actual',
    title: 'Planned vs Actual',
  },
  {
    description: 'Self-oriented dashboard for assignments, workload, and work evidence.',
    group: 'dashboard',
    path: '/dashboard/employee',
    title: 'Employee Dashboard',
    allowedRoles: ['hr_manager', 'director', 'admin'],
  },
  {
    description: 'Project-oriented dashboard for managed projects, staffing gaps, and anomalies.',
    group: 'dashboard',
    path: '/dashboard/project-manager',
    title: 'PM Dashboard',
    allowedRoles: ['project_manager', 'director', 'admin'],
  },
  {
    description: 'Capacity-oriented dashboard for managed teams, idle resources, and pipeline.',
    group: 'dashboard',
    path: '/dashboard/resource-manager',
    title: 'RM Dashboard',
    allowedRoles: ['resource_manager', 'director', 'admin'],
  },
  {
    description: 'Organization-centric dashboard for headcount, distribution, and people-data quality.',
    group: 'dashboard',
    path: '/dashboard/hr',
    title: 'HR Dashboard',
    allowedRoles: ['hr_manager', 'director', 'admin'],
  },
  {
    description: 'Team delivery dashboard for anomaly drilldown and delivery metrics.',
    group: 'dashboard',
    path: '/dashboard/delivery-manager',
    title: 'Delivery Dashboard',
    allowedRoles: ['delivery_manager', 'director', 'admin'],
  },
  {
    description: 'Organization structure and reporting visibility.',
    group: 'people-org',
    path: '/org',
    title: 'Org',
  },
  {
    description: 'Person × project allocation matrix for active assignments.',
    group: 'people-org',
    path: '/workload',
    title: 'Workload Matrix',
    allowedRoles: ['resource_manager', 'director', 'admin'],
  },
  {
    description: '12-week forward timeline of team assignment planning.',
    group: 'people-org',
    path: '/workload/planning',
    title: 'Workload Planning',
    allowedRoles: ['resource_manager', 'director', 'admin'],
  },
  {
    description: 'People directory and manager visibility.',
    group: 'people-org',
    path: '/people',
    title: 'People',
  },
  {
    description: 'Operational team management distinct from the organization hierarchy.',
    group: 'people-org',
    path: '/teams',
    title: 'Teams',
  },
  {
    description: 'Internal project registry and external links.',
    group: 'work',
    path: '/projects',
    title: 'Projects',
  },
  {
    description: 'Authoritative staffing assignments.',
    group: 'work',
    path: '/assignments',
    title: 'Assignments',
  },
  {
    description: 'Observed work evidence and reconciliation inputs.',
    group: 'work',
    path: '/work-evidence',
    title: 'Work Evidence',
  },
  {
    description: 'Weekly timesheet for logging project hours.',
    group: 'work',
    path: '/timesheets',
    title: 'My Timesheet',
  },
  {
    allowedRoles: ['employee', 'hr_manager', 'admin'],
    description: 'Submit and track leave requests. Managers can approve or reject pending requests.',
    group: 'work',
    path: '/leave',
    title: 'Time Off',
  },
  {
    description: 'Review and approve submitted timesheets.',
    group: 'work',
    path: '/timesheets/approval',
    title: 'Timesheet Approval',
    allowedRoles: ['project_manager', 'resource_manager', 'hr_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'Aggregated approved timesheet hours by project, person, and day.',
    group: 'work',
    path: '/reports/time',
    title: 'Time Report',
    allowedRoles: ['project_manager', 'resource_manager', 'hr_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'CAPEX/OPEX capitalisation breakdown for approved timesheets.',
    group: 'work',
    path: '/reports/capitalisation',
    title: 'Capitalisation',
    allowedRoles: ['director', 'admin', 'delivery_manager'],
  },
  {
    description: 'Generate and download XLSX reports for headcount, assignments, timesheets, capitalisation, and workload.',
    group: 'work',
    path: '/reports/export',
    title: 'Export Centre',
    allowedRoles: ['director', 'admin', 'delivery_manager', 'hr_manager'],
  },
  {
    description: 'Available vs assigned vs actual hours per person — utilization drill-down.',
    group: 'work',
    path: '/reports/utilization',
    title: 'Utilization',
    allowedRoles: ['project_manager', 'resource_manager', 'hr_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'Build custom reports from any data source, save templates, and export to XLSX.',
    group: 'work',
    path: '/reports/builder',
    title: 'Report Builder',
    allowedRoles: ['project_manager', 'resource_manager', 'hr_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'Onboarding and operational case workflows.',
    group: 'work',
    path: '/cases',
    title: 'Cases',
  },
  {
    description: 'Post and track staffing requests; resource managers propose candidates.',
    group: 'work',
    path: '/staffing-requests',
    title: 'Staffing Requests',
    allowedRoles: ['project_manager', 'resource_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'Conflict-aware drag-and-drop staffing board — move assignments between people.',
    group: 'work',
    path: '/staffing-board',
    title: 'Staffing Board',
    allowedRoles: ['resource_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'Named pools of people available for staffing allocation.',
    group: 'work',
    path: '/resource-pools',
    title: 'Resource Pools',
    allowedRoles: ['resource_manager', 'admin', 'director'],
  },
  {
    description: 'Unified operational queue for staffing, project, and reconciliation anomalies.',
    group: 'governance',
    path: '/exceptions',
    title: 'Exceptions',
    allowedRoles: ['project_manager', 'resource_manager', 'hr_manager', 'delivery_manager', 'director', 'admin'],
  },
  {
    description: 'External provider health and synchronization.',
    group: 'governance',
    path: '/integrations',
    title: 'Integrations',
    allowedRoles: ['director', 'admin'],
  },
  {
    description: 'Business-action audit trail for investigation and governance workflows.',
    group: 'admin',
    path: '/admin/audit',
    title: 'Business Audit',
    allowedRoles: ['hr_manager', 'director', 'admin'],
  },
  {
    description: 'Metadata-backed dictionary management for people-related configuration.',
    group: 'admin',
    path: '/admin/dictionaries',
    title: 'Admin Dictionaries',
    allowedRoles: ['hr_manager', 'director', 'admin'],
  },
  {
    description: 'Notification channel and template management.',
    group: 'admin',
    path: '/admin/notifications',
    title: 'Admin Notifications',
    allowedRoles: ['director', 'admin'],
  },
  {
    description: 'External provider health and synchronization.',
    group: 'admin',
    path: '/admin/integrations',
    title: 'Admin Integrations',
    allowedRoles: ['director', 'admin'],
  },
  {
    description: 'Read-only health, readiness, and diagnostics visibility.',
    group: 'admin',
    path: '/admin/monitoring',
    title: 'Admin Monitoring',
    allowedRoles: ['director', 'admin'],
  },
  {
    description: 'Consolidated operator-facing control surface for configuration and platform settings.',
    group: 'admin',
    path: '/admin',
    title: 'Admin',
    allowedRoles: ['admin'],
  },
  {
    description: 'Bulk import people from a CSV file — up to 200+ records at once.',
    group: 'admin',
    path: '/admin/people/import',
    title: 'Bulk Import',
    allowedRoles: ['admin', 'hr_manager'],
  },
  {
    description: 'Configure platform-wide behaviour: timesheets, capitalisation, pulse, notifications, and security.',
    group: 'admin',
    path: '/admin/settings',
    title: 'Platform Settings',
    allowedRoles: ['admin'],
  },
  {
    description: 'Metadata, validation, and administrative configuration.',
    group: 'admin',
    path: '/metadata-admin',
    title: 'Metadata / Admin',
    allowedRoles: ['admin'],
  },
  {
    description: 'Manage outbound webhook subscriptions with HMAC-SHA256 signed delivery.',
    group: 'admin',
    path: '/admin/webhooks',
    title: 'Webhooks',
    allowedRoles: ['admin'],
  },
  {
    description: 'Configure BambooHR or Workday HRIS integration for automated employee sync.',
    group: 'admin',
    path: '/admin/hris',
    title: 'HRIS Integration',
    allowedRoles: ['admin'],
  },
  {
    description: 'View and manage ABAC (Attribute-Based Access Control) policies per role and resource.',
    group: 'admin',
    path: '/admin/access-policies',
    title: 'Access Policies',
    allowedRoles: ['admin'],
  },
];
