/**
 * LEAN-P0-1 — readiness-check scaffold test.
 *
 * Verifies the SQL probes generated by buildProbes() are well-formed
 * without touching a live database. The goal is to catch:
 *   - missing probes
 *   - misnamed table / column references against the schema
 *   - structural omissions (no SELECT, no FROM, no violation_count alias)
 *
 * Live-DB behaviour is exercised by running the script against staging
 * during the LEAN migration sequence; this scaffold is a fast unit-level
 * smoke test only.
 */

import { buildProbes } from '../../../scripts/lean-readiness-check';

describe('lean-readiness-check buildProbes()', () => {
  const probes = buildProbes();

  it('returns the five expected probes in stable order', () => {
    expect(probes.map((p) => p.name)).toEqual([
      'assignment_backfill_completeness',
      'staffing_request_backfill_completeness',
      'status_mapping_consistency',
      'candidate_backfill_completeness',
      'headcount_parity',
    ]);
  });

  it('every probe carries a non-empty description', () => {
    for (const p of probes) {
      expect(p.description.length).toBeGreaterThan(10);
    }
  });

  it('every probe SQL is non-empty and selects violation_count + sample_id', () => {
    for (const p of probes) {
      expect(p.sql.trim().length).toBeGreaterThan(0);
      expect(p.sql).toMatch(/SELECT/i);
      expect(p.sql).toMatch(/violation_count/);
      expect(p.sql).toMatch(/sample_id/);
    }
  });

  it('probes reference only the documented schema tables', () => {
    const allowedTables = new Set([
      'ProjectAssignment',
      'ProjectPosition',
      'ProjectPositionCandidate',
      'StaffingRequestProposalCandidate',
      'StaffingRequestProposalSlate',
      'staffing_requests',
    ]);
    const tableRefRegex = /"([A-Za-z_][A-Za-z0-9_]*)"\s+(?:[A-Za-z_][A-Za-z0-9_]*)/g;
    for (const p of probes) {
      let match: RegExpExecArray | null;
      while ((match = tableRefRegex.exec(p.sql)) !== null) {
        const ident = match[1];
        // Skip column references (lowercase quoted identifiers that are
        // not in the table set) — the heuristic above will sometimes catch
        // column aliases; we narrow to the recognised-table family only.
        if (/^[A-Z]/.test(ident) || ident === 'staffing_requests') {
          if (!allowedTables.has(ident)) {
            // Identifier doesn't match a known table — fail loudly so the
            // probe author knows they referenced an unknown relation.
            throw new Error(
              `probe ${p.name} references unknown table "${ident}"`,
            );
          }
        }
      }
    }
  });

  it('status_mapping_consistency embeds the full legacy→lean map (11 main + 6 pre-CSW)', () => {
    const probe = probes.find((p) => p.name === 'status_mapping_consistency');
    expect(probe).toBeDefined();
    // Each VALUES row is of shape "('LEGACY', 'LEAN')" — there should be
    // at least 17 such rows (the 11 main AssignmentStatus values + 6
    // pre-CSW legacy values inlined for backward compatibility).
    const matches = (probe!.sql.match(/\('[A-Z_]+',\s*'[A-Z_]+'\)/g) ?? []);
    expect(matches.length).toBeGreaterThanOrEqual(17);
    // Must include the lossy collapses that the audit doc documents.
    expect(probe!.sql).toContain("('REJECTED', 'RELEASED')");
    expect(probe!.sql).toContain("('COMPLETED', 'RELEASED')");
    expect(probe!.sql).toContain("('CANCELLED', 'RELEASED')");
    expect(probe!.sql).toContain("('CREATED', 'OPEN')");
    expect(probe!.sql).toContain("('IN_REVIEW', 'PROPOSED')");
  });

  it('candidate_backfill probe joins via legacyStaffingRequestId', () => {
    const probe = probes.find((p) => p.name === 'candidate_backfill_completeness');
    expect(probe).toBeDefined();
    expect(probe!.sql).toContain('legacyStaffingRequestId');
    expect(probe!.sql).toContain('candidatePersonId');
  });

  it('headcount_parity probe compares against staffing_requests.headcountRequired', () => {
    const probe = probes.find((p) => p.name === 'headcount_parity');
    expect(probe).toBeDefined();
    expect(probe!.sql).toContain('headcountRequired');
    expect(probe!.sql).toContain('staffing_requests');
  });

  it('probe names are unique', () => {
    const names = probes.map((p) => p.name);
    expect(new Set(names).size).toBe(names.length);
  });
});
