/**
 * LEAN-P0-3 — dual-ID hazard audit scaffold test.
 *
 * Verifies the four SQL audits generated by buildAudits() are well-formed
 * and reference only the schema relations documented in
 * docs/planning/lean-dual-id-hazards.md, without touching a live database.
 *
 * Live-DB behaviour is exercised by running the script against staging
 * during the LEAN migration sequence; this scaffold is the fast unit-level
 * smoke test that keeps the four probes in stable shape.
 */

import { buildAudits } from '../../../scripts/lean-dual-id-audit';

describe('lean-dual-id-audit buildAudits()', () => {
  const audits = buildAudits();

  it('returns the four expected audits in stable order matching the hazard doc', () => {
    expect(audits.map((a) => a.name)).toEqual([
      'staffing_request_id_promotion_ready',
      'staffing_request_fulfilment_id_promotion_ready',
      'timesheet_entry_assignment_orphan_check',
      'case_record_assignment_orphan_check',
    ]);
  });

  it('every audit carries a hazard index 1..4 in order', () => {
    expect(audits.map((a) => a.hazard)).toEqual([1, 2, 3, 4]);
  });

  it('hazard indices are unique', () => {
    const hazards = audits.map((a) => a.hazard);
    expect(new Set(hazards).size).toBe(hazards.length);
  });

  it('audit names are unique', () => {
    const names = audits.map((a) => a.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it('every audit carries a non-empty description', () => {
    for (const a of audits) {
      expect(a.description.length).toBeGreaterThan(10);
    }
  });

  it('every audit SQL is non-empty and selects violation_count + sample_id', () => {
    for (const a of audits) {
      expect(a.sql.trim().length).toBeGreaterThan(0);
      expect(a.sql).toMatch(/SELECT/i);
      expect(a.sql).toMatch(/violation_count/);
      expect(a.sql).toMatch(/sample_id/);
    }
  });

  it('every audit SQL ends with a terminating semicolon', () => {
    for (const a of audits) {
      expect(a.sql.trim().endsWith(';')).toBe(true);
    }
  });

  it('audits reference only the documented schema tables', () => {
    const allowedTables = new Set([
      'staffing_requests',
      'staffing_request_fulfilments',
      'timesheet_entries',
      'ProjectAssignment',
      'ProjectPosition',
      'CaseRecord',
    ]);
    // Matches a quoted identifier immediately followed by an alias or the
    // start of a clause — same heuristic as LEAN-P0-1 readiness check.
    const tableRefRegex = /"([A-Za-z_][A-Za-z0-9_]*)"\s+(?:[A-Za-z_][A-Za-z0-9_]*)/g;
    for (const a of audits) {
      let match: RegExpExecArray | null;
      while ((match = tableRefRegex.exec(a.sql)) !== null) {
        const ident = match[1];
        // Filter to identifiers that look table-shaped: PascalCase or
        // snake_case plurals seen in this schema.
        if (
          /^[A-Z]/.test(ident) ||
          ident === 'staffing_requests' ||
          ident === 'staffing_request_fulfilments' ||
          ident === 'timesheet_entries'
        ) {
          if (!allowedTables.has(ident)) {
            throw new Error(
              `audit ${a.name} references unknown table "${ident}"`,
            );
          }
        }
      }
    }
  });

  it('hazard 1 audit checks `id_new` on staffing_requests', () => {
    const audit = audits.find((a) => a.hazard === 1);
    expect(audit).toBeDefined();
    expect(audit!.sql).toContain('"staffing_requests"');
    expect(audit!.sql).toContain('"id_new" IS NULL');
  });

  it('hazard 2 audit checks `id_new` on staffing_request_fulfilments', () => {
    const audit = audits.find((a) => a.hazard === 2);
    expect(audit).toBeDefined();
    expect(audit!.sql).toContain('"staffing_request_fulfilments"');
    expect(audit!.sql).toContain('"id_new" IS NULL');
  });

  it('hazard 3 audit joins timesheet_entries.assignmentId to ProjectPosition.legacyAssignmentId', () => {
    const audit = audits.find((a) => a.hazard === 3);
    expect(audit).toBeDefined();
    expect(audit!.sql).toContain('"timesheet_entries"');
    expect(audit!.sql).toContain('"ProjectPosition"');
    expect(audit!.sql).toContain('"assignmentId"');
    expect(audit!.sql).toContain('"legacyAssignmentId"');
  });

  it('hazard 4 audit joins CaseRecord.relatedAssignmentId to ProjectPosition.legacyAssignmentId', () => {
    const audit = audits.find((a) => a.hazard === 4);
    expect(audit).toBeDefined();
    expect(audit!.sql).toContain('"CaseRecord"');
    expect(audit!.sql).toContain('"ProjectPosition"');
    expect(audit!.sql).toContain('"relatedAssignmentId"');
    expect(audit!.sql).toContain('"legacyAssignmentId"');
  });

  it('orphan-check audits use NOT EXISTS to surface unmatched rows', () => {
    const orphanAudits = audits.filter((a) => a.hazard === 3 || a.hazard === 4);
    expect(orphanAudits).toHaveLength(2);
    for (const a of orphanAudits) {
      expect(a.sql).toMatch(/NOT EXISTS/i);
    }
  });
});
