-- F-7.4 / D-164 — multi-currency consolidation table.
--
-- Index + FK names match Prisma's auto-generated conventions so
-- `prisma migrate diff` sees no drift. UUID `id` is generated by
-- Prisma in app code (no Postgres DEFAULT).
--
-- Forward: create `fx_rates` with unique on (from, to, asOf), a
-- desc-on-asOf composite for "latest rate" lookups, and a toCurrency
-- index to satisfy the FK-index ratchet.
-- Rollback: drop the table + indexes.

CREATE TABLE IF NOT EXISTS "fx_rates" (
  "id"            UUID NOT NULL,
  "fromCurrency"  VARCHAR(3) NOT NULL,
  "toCurrency"    VARCHAR(3) NOT NULL,
  "rate"          DECIMAL(18, 8) NOT NULL,
  "asOf"          DATE NOT NULL,
  "source"        TEXT,
  "createdAt"     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fx_rates_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "fx_rates" ADD CONSTRAINT "fx_rates_fromCurrency_fkey"
    FOREIGN KEY ("fromCurrency") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "fx_rates" ADD CONSTRAINT "fx_rates_toCurrency_fkey"
    FOREIGN KEY ("toCurrency") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "fx_rates_fromCurrency_toCurrency_asOf_key"
  ON "fx_rates" ("fromCurrency", "toCurrency", "asOf");

CREATE INDEX IF NOT EXISTS "fx_rates_fromCurrency_toCurrency_asOf_idx"
  ON "fx_rates" ("fromCurrency", "toCurrency", "asOf" DESC);

CREATE INDEX IF NOT EXISTS "fx_rates_toCurrency_idx"
  ON "fx_rates" ("toCurrency");
