/** Standard IT / software delivery staffing roles dictionary. */
export const STAFFING_ROLES = [
  'Software Engineer',
  'Senior Software Engineer',
  'Lead Engineer',
  'Staff Engineer',
  'Principal Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Full-Stack Engineer',
  'Mobile Engineer',
  'DevOps Engineer',
  'SRE Engineer',
  'Platform Engineer',
  'Data Engineer',
  'ML Engineer',
  'QA Engineer',
  'SDET',
  'Automation Engineer',
  'Security Engineer',
  'Cloud Architect',
  'Solutions Architect',
  'Technical Architect',
  'Engineering Manager',
  'Tech Lead',
  'Team Lead',
  'Scrum Master',
  'Agile Coach',
  'Project Manager',
  'Delivery Manager',
  'Product Owner',
  'Product Manager',
  'Business Analyst',
  'Systems Analyst',
  'UX Designer',
  'UI Designer',
  'UX Researcher',
  'Technical Writer',
  'Release Manager',
  'Database Administrator',
  'Support Engineer',
  'Integration Specialist',
] as const;

export type StaffingRole = typeof STAFFING_ROLES[number];
